-- Create Movies Table (If not exists)
CREATE TABLE IF NOT EXISTS movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    thumbnail TEXT,
    video_url TEXT,
    download_link TEXT,
    description TEXT,
    category TEXT, -- Comma separated: "Trending Now, Latest Releases, Top Rated"
    type TEXT DEFAULT 'movie', -- movie or tv
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ADD MISSING COLUMNS (Run this if you already created the table)
ALTER TABLE movies ADD COLUMN IF NOT EXISTS year TEXT;
ALTER TABLE movies ADD COLUMN IF NOT EXISTS genre TEXT;
ALTER TABLE movies ADD COLUMN IF NOT EXISTS duration TEXT;
ALTER TABLE movies ADD COLUMN IF NOT EXISTS rating TEXT;

-- Create Featured Movie Table
CREATE TABLE IF NOT EXISTS featured_movie (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    backdrop_url TEXT,
    year TEXT,
    rating TEXT,
    duration TEXT,
    genre TEXT,
    download_link TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- VISITOR COUNT TABLE
CREATE TABLE IF NOT EXISTS site_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_name TEXT UNIQUE NOT NULL, 
    value INT DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Initialize counter if not exists
INSERT INTO site_stats (key_name, value) 
VALUES ('total_visits', 0) 
ON CONFLICT (key_name) DO NOTHING;
